#!/usr/bin/env python3
"""
embed-assets.py — Convert asset files (HTML, CSS) into a C header string.

Usage:
    python3 tools/embed-assets.py <assets_dir> <output.h>

The generated header provides:
    #define PAGE_CAPTIVE  "HTTP/1.1 200 OK\r\n..."

The HTML can reference "style.css" — the script inlines it automatically.
"""

import os
import sys


def escape_c_string(data: bytes) -> str:
    """Convert bytes to a C string literal with \\r\\n, \\" etc."""
    result = []
    for b in data:
        if b == ord(b'"'):
            result.append('\\"')
        elif b == ord(b'\\'):
            result.append('\\\\')
        elif b == ord(b'\r'):
            result.append('\\r')
        elif b == ord(b'\n'):
            result.append('\\n')
        elif 32 <= b < 127:
            result.append(chr(b))
        else:
            result.append(f'\\x{b:02x}')
    return ''.join(result)


def read_file(path: str) -> bytes:
    with open(path, 'rb') as f:
        return f.read()


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <assets_dir> <output.h>", file=sys.stderr)
        sys.exit(1)

    assets_dir = sys.argv[1]
    output_path = sys.argv[2]

    # Read asset files
    html_path = os.path.join(assets_dir, 'index.html')
    css_path = os.path.join(assets_dir, 'style.css')

    if not os.path.isfile(html_path):
        print(f"Error: {html_path} not found", file=sys.stderr)
        sys.exit(1)

    html_raw = read_file(html_path).decode('utf-8')

    # If CSS exists, inline it into the HTML (replace <link> with <style>)
    if os.path.isfile(css_path):
        css_raw = read_file(css_path).decode('utf-8')
        # Replace <link rel="stylesheet" href="style.css"> with inline <style>
        html_raw = html_raw.replace('<link rel="stylesheet" href="style.css">',
                                    f'<style>\n{css_raw}\n</style>')
        # Also handle single-quote variant
        html_raw = html_raw.replace("<link rel='stylesheet' href='style.css'>",
                                    f'<style>\n{css_raw}\n</style>')

    # Build the full HTTP response
    http_response = (
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html\r\n"
        "Connection: close\r\n"
        "\r\n"
        f"{html_raw}\r\n"
    )

    # Escape to C string
    escaped = escape_c_string(http_response.encode('utf-8'))

    # Write output header
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    with open(output_path, 'w') as f:
        f.write("/* Auto-generated by embed-assets.py — do not edit */\n")
        f.write("#ifndef ASSETS_PAGE_CAPTIVE_H\n")
        f.write("#define ASSETS_PAGE_CAPTIVE_H\n\n")
        f.write(f'#define PAGE_CAPTIVE "{escaped}"\n\n')
        f.write("#endif /* ASSETS_PAGE_CAPTIVE_H */\n")

    print(f"✅ Generated {output_path}")
    print(f"   Response size: {len(http_response)} bytes")


if __name__ == '__main__':
    main()
