#!/usr/bin/env python3
"""
embed-assets.py — Convert asset files (HTML, CSS) into C header string macros.

Usage:
    python3 tools/embed-assets.py <assets_dir> <output.h>

The generated header provides:
    #define PAGE_CAPTIVE  "HTTP/1.1 200 OK\r\n..."   (from index.html)
    #define PAGE_SPLIT    "HTTP/1.1 200 OK\r\n..."   (from split.html)
    #define PAGE_UNSPLIT  "HTTP/1.1 200 OK\r\n..."   (from unsplit.html)

Each HTML can reference "style.css" — the script inlines it automatically.
"""

import os
import sys


def escape_c_string(data: bytes) -> str:
    """Convert bytes to a C string literal with \\r\\n, \\" etc."""
    result = []
    for b in data:
        if b == ord(b'"'):
            result.append('\\"')
        elif b == ord(b'\\'):
            result.append('\\\\')
        elif b == ord(b'\r'):
            result.append('\\r')
        elif b == ord(b'\n'):
            result.append('\\n')
        elif 32 <= b < 127:
            result.append(chr(b))
        else:
            result.append(f'\\x{b:02x}')
    return ''.join(result)


def read_file(path: str) -> bytes:
    with open(path, 'rb') as f:
        return f.read()


def build_page(html_raw: str, css_raw: str | None, assets_dir: str) -> str:
    """Inline CSS and JS into HTML, then wrap with HTTP response headers."""
    if css_raw is not None:
        html_raw = html_raw.replace('<link rel="stylesheet" href="style.css">',
                                    f'<style>\n{css_raw}\n</style>')
        html_raw = html_raw.replace("<link rel='stylesheet' href='style.css'>",
                                    f'<style>\n{css_raw}\n</style>')

    # Inline JavaScript files: <script src="scripts/foo.js"></script>
    import re
    def inline_js(match):
        src = match.group(1)
        js_path = os.path.join(assets_dir, src)
        if os.path.isfile(js_path):
            js_raw = read_file(js_path).decode('utf-8')
            return f'<script>\n{js_raw}\n</script>'
        return match.group(0)  # file not found — leave as-is

    html_raw = re.sub(
        r'<script\s+src="([^"]+)"\s*></script>',
        inline_js,
        html_raw,
    )

    return (
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html\r\n"
        "Connection: close\r\n"
        "\r\n"
        f"{html_raw}\r\n"
    )


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <assets_dir> <output.h>", file=sys.stderr)
        sys.exit(1)

    assets_dir = sys.argv[1]
    output_path = sys.argv[2]

    # Read CSS once — shared by all pages
    css_path = os.path.join(assets_dir, 'style.css')
    css_raw = None
    if os.path.isfile(css_path):
        css_raw = read_file(css_path).decode('utf-8')

    # Define pages: (html_filename, macro_name)
    pages = [
        ('index.html',  'PAGE_CAPTIVE'),
        ('split.html',  'PAGE_SPLIT'),
        ('unsplit.html','PAGE_UNSPLIT'),
    ]

    # Write output header
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    with open(output_path, 'w') as f:
        f.write("/* Auto-generated by embed-assets.py — do not edit */\n")
        f.write("#ifndef ASSETS_PAGE_CAPTIVE_H\n")
        f.write("#define ASSETS_PAGE_CAPTIVE_H\n\n")

        for html_name, macro_name in pages:
            html_path = os.path.join(assets_dir, html_name)
            if not os.path.isfile(html_path):
                print(f"Warning: {html_path} not found, skipping {macro_name}", file=sys.stderr)
                continue

            html_raw = read_file(html_path).decode('utf-8')
            http_response = build_page(html_raw, css_raw, assets_dir)
            escaped = escape_c_string(http_response.encode('utf-8'))
            f.write(f'#define {macro_name} "{escaped}"\n\n')

            size = len(http_response)
            print(f"  {macro_name:20s} {size:5d} bytes  ({html_name})")

        f.write("#endif /* ASSETS_PAGE_CAPTIVE_H */\n")

    print(f"✅ Generated {output_path}")


if __name__ == '__main__':
    main()
